server:
  port: 8083
spring:
  application:
    name: RecordsMemorandum
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8087/eureka
    fetch-registry: false
    register-with-eureka: true
ribbon:
      #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
      #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
          # feign日志以什么级别监控哪个接口
    com.tianfei.springcloud.service.PaymentFeignService: debug
          # com.tianfei.springcloud.service.PaymentFeignService 这个是暴露服务提供者接口的类名